export const FETCH_USER = "FETCH_USER";
export const ADD_LOCATION = "ADD_LOCATION";
export const REMOVE_LOCATION = "REMOVE_LOCATION";
export const FETCH_JOURNEYS = "FETCH_JOURNEYS";
export const FETCH_ACTIVE_JOURNEYS = "FETCH_ACTIVE_JOURNEYS";
export const FETCH_INACTIVE_JOURNEYS = "FETCH_INACTIVE_JOURNEYS";
