export const FETCH_USER = "FETCH_USER";
export const FETCH_JOURNEYS = "FETCH_JOURNEYS";
export const FETCH_ACTIVE_JOURNEYS = "FETCH_ACTIVE_JOURNEYS";
export const FETCH_INACTIVE_JOURNEYS = "FETCH_INACTIVE_JOURNEYS";
